### ISSUE TITLE
Regex matching doesn't work

### ISSUE THREAD

**Issue by ostrolucky** [elecprog/tldr#1]
README says

> If you want all the commands matching a grep style regex, let's say g[ie]t$, use:
>> tldr -s 'g[ie]t$'

But it doesn't work:

```
➜ tldr -u           
already up-to-date
➜ tldr -s '^g[ie]t$'
This page (^g[ie]t$) doesn't exist yet!
Submit new pages here: https://github.com/tldr-pages/tldr%                                                                                                                                                                            ➜ 
```

**Comment by eprovst** [comment]
May I ask how you installed the client (go's tooling or a build) and the output of `tldr --version`? :slightly_smiling_face:

**Comment by ostrolucky** [comment]
Ah my bad, that's actually different go package. This one doesn't install though, will create new issue
