### ISSUE TITLE
undefined: os.UserCacheDir when installing

### ISSUE THREAD

**Issue by ostrolucky** [elecprog/tldr#2]
```
➜  ~ go get github.com/elecprog/tldr
# github.com/elecprog/tldr/cli
go/src/github.com/elecprog/tldr/cli/info.go:27:14: undefined: os.UserCacheDir
➜  ~
``

**Comment by eprovst** [comment]
May I ask what OS you are using and/or the Go version? :slightly_smiling_face:

**Comment by eprovst** [comment]
This was added in the 1.11 series, I will look for a fix for older Go versions (this is prohibitive on Debian derivatives).

**Comment by ostrolucky** [comment]
```
➜  ~ go version    
go version go1.10.4 linux/amd64
➜  ~ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

➜  ~
```

**Comment by eprovst** [comment]
Please retry, should be fixed since latest commit :slightly_smiling_face:

**Comment by ostrolucky** [comment]
It does! gj

**Comment by eprovst** [comment]
Thanks for the report :slightly_smiling_face:
